### ISSUE TITLE
krunner hangs after copying password after already copied additional action

### ISSUE THREAD

**Issue by msmol** [akermu/krunner-pass#9]
With the following `krunner-pass` settings:
```
[Runners][Pass]
showAdditionalActions=true
showFullFileContentAction=false

[Runners][Pass][AdditionalActions][0]
Icon=user-identity
Name=Login
Regex=^login: (.+?)$
```
After doing a copy using the new `Login` action (which works), the _next_ use of `krunner-pass` to copy the password causes `krunner` to hang. At this point I need to kill the process and restart `krunner`.

`krunner` does _not_ hang if I try to copy the `Login` (or any other additional action) a second time, only when doing 

1. Copy an additional action entry (using tab -> return, or a click on the icon)
2. Copy password (using return or click)

in that exact order.

Happens every time, using Arch Linux with all the latest updates.

**Comment by akermu** [comment]
I can reproduce the issue here. I will probably have time on the weekend to debug it. Thanks for the report!

**Comment by isamert** [comment]
It may be something related with the `QTimer::singleShot` usage in the lambda function. Because after waiting awhile, password copying works. I don't know how to solve it and I can't try anything at the moment but simply removing it would probably solve the issue. But not clearing the clipboard is not the wanted behavior. There should be some workaround for this.

**Comment by akermu** [comment]
If you comment out line 198, krunner doesn't hang, but I still couldn't find out why or how to fix it..
